// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpellStack.Api.Data;

#nullable disable

namespace SpellStack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723163941_AddTranslationContextAndVariants")]
    partial class AddTranslationContextAndVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpellStack.Api.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestTrialStars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ContentRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HighScore")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LearningLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TranslationLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TrialResultRevision")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks", t =>
                        {
                            t.HasCheckConstraint("CK_Decks_BestTrialStars", "\"BestTrialStars\" >= 0 AND \"BestTrialStars\" <= 3");
                        });
                });

            modelBuilder.Entity("SpellStack.Api.Models.GameRunResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageResponseTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<string>("EndReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("HighestCombo")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("LongestRushHourDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ModifiersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoundLimit")
                        .HasColumnType("integer");

                    b.Property<int>("RushHoursCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("RushHoursTriggered")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("GameRunResults");
                });

            modelBuilder.Entity("SpellStack.Api.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWordId")
                        .HasColumnType("integer");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Lives")
                        .HasColumnType("integer");

                    b.Property<double?>("LongestRushHourDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("ModifiersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionsAnswered")
                        .HasColumnType("integer");

                    b.Property<bool>("ResultSaved")
                        .HasColumnType("boolean");

                    b.Property<int?>("RoundLimit")
                        .HasColumnType("integer");

                    b.Property<int>("RushHoursCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("RushHoursTriggered")
                        .HasColumnType("integer");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer");

                    b.Property<double?>("TotalResponseTimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWordId");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("SpellStack.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SpellStack.Api.Models.TranslationCacheEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedSourceLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedContext")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("NormalizedSourceText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestVariant")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ResolvedTargetLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TranslationText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("SourceLanguage", "ResolvedTargetLanguage", "NormalizedSourceText", "NormalizedContext", "RequestVariant")
                        .IsUnique();

                    b.ToTable("TranslationCacheEntries");
                });

            modelBuilder.Entity("SpellStack.Api.Models.UpdatePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("UpdatePosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Core",
                            Content = "SpellStack's first playable release established the core vocabulary-practice experience.\n\n- Account and profile flow\n- Custom vocabulary decks\n- Core quiz and battle gameplay loop\n- Themes and settings\n- Production deployment foundation",
                            CreatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "v0-1-0-early-spellstack-build",
                            Status = "Live",
                            Summary = "Initial playable SpellStack build with accounts, decks and gameplay.",
                            Title = "Early SpellStack Build",
                            UpdatedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Version = "v0.1.0"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Polish",
                            Content = "This release made themes more dependable and the interface easier to read across different backgrounds.\n\n- Adjusted default theme behavior\n- Improved gradient and solid theme support\n- More reliable custom background loading\n- Continued UI readability polish",
                            CreatedAt = new DateTime(2026, 7, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "v0-1-5-theme-ui-polish",
                            Status = "Live",
                            Summary = "Improved visual polish and theme behavior across SpellStack.",
                            Title = "Theme & UI Polish",
                            UpdatedAt = new DateTime(2026, 7, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            Version = "v0.1.5"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Responsive",
                            Content = "SpellStack now adapts more intentionally to the screen it is played on.\n\n- Responsive layouts for desktop, tablet and mobile\n- Improved navigation across screen sizes\n- Profile, deck and gameplay layout polish\n- Better mobile gameplay readability and usability",
                            CreatedAt = new DateTime(2026, 7, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "v0-2-0-responsive-design",
                            Status = "Live",
                            Summary = "Improved SpellStack across desktop, tablet and mobile layouts.",
                            Title = "Responsive Design",
                            UpdatedAt = new DateTime(2026, 7, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Version = "v0.2.0"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Multiplayer",
                            Content = "The multiplayer lobby now has a real realtime foundation while keeping gameplay setup familiar.\n\n- Private rooms with shareable room codes\n- Live player list and ready state\n- SignalR room communication\n- Leave and reconnect-aware room handling",
                            CreatedAt = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "v0-3-0-realtime-multiplayer-lobby",
                            Status = "Live",
                            Summary = "Added the first realtime multiplayer foundation to SpellStack.",
                            Title = "Realtime Multiplayer Lobby",
                            UpdatedAt = new DateTime(2026, 7, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Version = "v0.3.0"
                        });
                });

            modelBuilder.Entity("SpellStack.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomLoginSplashSoundUrl")
                        .HasColumnType("text");

                    b.Property<string>("CustomMainMenuMusicUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FavoriteLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ThemeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpellStack.Api.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("SpellStack.Api.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("SpellStack.Api.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativeOriginal")
                        .HasColumnType("text");

                    b.Property<string>("AlternativeTranslation")
                        .HasColumnType("text");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<string>("Hint")
                        .HasColumnType("text");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("SpellStack.Api.Models.Deck", b =>
                {
                    b.HasOne("SpellStack.Api.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellStack.Api.Models.GameRunResult", b =>
                {
                    b.HasOne("SpellStack.Api.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellStack.Api.Models.GameSession", "GameSession")
                        .WithMany()
                        .HasForeignKey("GameSessionId");

                    b.HasOne("SpellStack.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("GameSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellStack.Api.Models.GameSession", b =>
                {
                    b.HasOne("SpellStack.Api.Models.Word", "CurrentWord")
                        .WithMany()
                        .HasForeignKey("CurrentWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellStack.Api.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellStack.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWord");

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellStack.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("SpellStack.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellStack.Api.Models.UserAchievement", b =>
                {
                    b.HasOne("SpellStack.Api.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellStack.Api.Models.UserSession", b =>
                {
                    b.HasOne("SpellStack.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellStack.Api.Models.Word", b =>
                {
                    b.HasOne("SpellStack.Api.Models.Deck", "Deck")
                        .WithMany("Words")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("SpellStack.Api.Models.Deck", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("SpellStack.Api.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
